.MODEL SMALL
.STACK 100H

DATA SEGMENT
    MSG DB "DECREMENT THE DIFFERENCE$"
    MSG1 DB 'ENTER FIRST NUMBER : $'
    MSG2 DB 'ENTER SECOND NUMBER : $'
    MSG3 DB 'THE DECREMENT OF ' ;SENTENCE CONTINUES...  
    ;TO INITIALIZE  
    NUM1 DB ?
    MSG4 DB '-'
    NUM2 DB ?, ' IS : '
    DIFFERENCE DB ?,'$' 
    CR DB 0DH, 0AH, '$'
ENDS

CODE SEGMENT  
    ASSUME DS:DATA CS:CODE
MAIN:
    MOV AX, DATA     ;INITIALIZATION
    MOV DS, AX
    
    LEA DX,MSG       ;LOAD AND DISPLAY TITLE
    MOV AH, 9
    INT 21H 
    
    LEA DX, CR      ;CARRIAGE RETURN FORM FEED
    MOV AH, 9H
    INT 21H
    
    LEA DX, CR      ;CARRIAGE RETURN FORM FEED
    MOV AH, 9H
    INT 21H
    
    LEA DX, MSG1     ;LOAD AND DISPLAY MSG1
    MOV AH, 9H
    INT 21H

    MOV AH, 1H       ;READS CHARACTER INPUT
    INT 21H

    MOV NUM1, AL     ;STORE NUM1
    MOV BH, AL
    SUB BH, '0'

    LEA DX, CR      ;CARRIAGE RETURN FORM FEED
    MOV AH, 9H
    INT 21H
                    
    LEA DX, MSG2    ;LOAD AND DISPLAY MSG2
    MOV AH, 9H
    INT 21H

    MOV AH, 1H      ;READS CHARACTER INPUT
    INT 21H

    MOV NUM2, AL    ;STORE NUM2
    MOV BL, AL
    SUB BL, '0'
                    
    SUB BH, BL      ;SUBTRACTS THE VARIABLES AND CONVERTS TO CHARACTER AND SAVE
    ADD BH, '0'
    MOV DIFFERENCE, BH 
    DEC DIFFERENCE  ;DECREMENT DIFFERENCE
                    
    LEA DX, CR      ;CARRIAGE RETURN FORM FEED
    MOV AH, 9H
    INT 21H
                    
    LEA DX, MSG3    ;DISPLAY RESULT
    MOV AH, 9H
    INT 21H        

    MOV AH, 4CH     ;RETURN TO DOS
    INT 21H

ENDS
END MAIN