.MODEL SMALL
.STACK 100H

DATA SEGMENT 
    MSG DB "INCREMENT THE SUM$"
    MSG1 DB "ENTER FIRST NUMBER : $"
    MSG2 DB 10,13,"ENTER SECOND NUMBER : $"
    MSG3 DB 10,13,"INCREMENT OF TWO NUMBERS is : $"     
    ;TO INITIALIZE
    NUM1 DB ?
    NUM2 DB ?
    RESULT DB ? 
    CR DB 0DH, 0AH, '$'
ENDS 

CODE SEGMENT
    ASSUME DS:DATA CS:CODE
MAIN:
    MOV AX,DATA      ;INITIALIZATION
    MOV DS,AX
    
    LEA DX,MSG       ;LOAD AND DISPLAY TITLE
    MOV AH, 9
    INT 21H 
    
    LEA DX, CR      ;CARRIAGE RETURN FORM FEED
    MOV AH, 9H
    INT 21H
    
    LEA DX, CR      ;CARRIAGE RETURN FORM FEED
    MOV AH, 9H
    INT 21H
    
    LEA DX,MSG1      ;LOAD AND DISPLAY MSG1
    MOV AH,9
    INT 21H

    MOV AH,1         ;READS CHARACTER INPUT
    INT 21H

    SUB AL,30H       ;SUBTRACTING 30H FROM AL TO GET ITS BINARY CODED DECIMAL
    MOV NUM1,AL

    LEA DX,MSG2      ;LOAD AND DISPLAY MSG2
    MOV AH,9
    INT 21H

    MOV AH,1         ;READS CHARACTER INPUT
    INT 21H

    SUB AL,30H       ;SUBTRACTING 30H FROM AL TO GET ITS BINARY CODED DECIMAL
    MOV NUM2,AL   
    
    ADD AL,NUM1      ;ADD 2 VARIABLES = RESULT
    MOV RESULT,AL
    
    MOV AH,0         ;TO CLEAN UNWANTED VALUES
    AAA              ;ASCII Adjust after Addition
    
    ADD AH,30H       ;Coresponding Ascii Code of the number
    ADD AL,30H 
    
    MOV BX,AX

    LEA DX,MSG3      ;LOAD AND DISPLAY MSG3
    MOV AH,9
    INT 21H
    
    MOV AH,2         ;DISPLAY CHARACTER STORED IN BH
    MOV DL,BH
    INT 21H
    
    MOV AH,2         ;DISPLAY CHARACTER STORED IN BL
    MOV DL,BL        
    INC DL           ;INCREMENT THE SUM OF 2 NUMBERS
    INT 21H    
    

    MOV AH,4CH       ;RETURN TO DOS
    INT 21H

ENDS
END MAIN